package io.github.zrdzn.web.chattee.backend.shared;

public enum DomainError {

    SQL_EXCEPTION,

    DISCUSSION_ALREADY_EXISTS,
    DISCUSSION_NOT_EXISTS,

    AUTH_DETAILS_ALREADY_EXIST,
    AUTH_DETAILS_NOT_EXIST,

    ACCOUNT_ALREADY_EXISTS,
    ACCOUNT_NOT_EXISTS,
    ACCOUNT_INVALID_ID,

    ACCOUNT_PRIVILEGE_NOT_EXISTS,

}
